---
- name:
  postgresql_membership:
    group: "{{ item.group }}"
    target_roles: "{{ item.target_roles }}"
    state: "{{ item.state | default('present') }}"
    port: "{{ item.port | default(postgresql_port) }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories[0]) }}"
  with_items: "{{ postgresql_memberships }}"
  become: true
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
